parameters:
    carousel_images:
        - 'baner-1.jpg'
        - 'baner-2.jpg'
        - 'baner-1.jpg'
        - 'baner-2.jpg'
        - 'baner-1.jpg'
        - 'baner-2.jpg'
        
    video.class:                Dende\PolmediaBundle\Entity\Video
    video_repository.class:     Dende\PolmediaBundle\Entity\VideoRepository
    category.class:             Dende\PolmediaBundle\Entity\Category
    category_repository.class:  Dende\PolmediaBundle\Entity\CategoryRepository

services:
    video_repository:
        class:                  Doctrine\Common\Persistence\ObjectRepository
        factory_service:        doctrine
        factory_method:         getRepository
        arguments:              [ "%video.class%" ]
    category_repository:
        class:                  Doctrine\Common\Persistence\ObjectRepository
        factory_service:        doctrine
        factory_method:         getRepository
        arguments:              [ "%category.class%" ]
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    dende.upload_listener:
        class: Dende\PolmediaBundle\Services\Listener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event : oneup_uploader.post_persist, method: onUpload}
    dende.image_rescale_listener:
        class: Dende\PolmediaBundle\Services\Listener\ImageRescaleListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event : oneup_uploader.post_persist, method: onUpload}
#    dende.update_orders_listener:
#        class: Dende\PolmediaBundle\EventListener\UpdateOrders
#        tags:
#            - { name: doctrine.event_listener, event: postFlush, connection: default }

    gedmo.listener.softdeleteable:
      class: Gedmo\SoftDeleteable\SoftDeleteableListener
      tags:
          - { name: doctrine.event_subscriber, connection: default }
      calls:
          - [ setAnnotationReader, [ @annotation_reader ] ]