<?php

namespace Dende\PolmediaBundle\Entity;

use Dende\PolmediaBundle\Entity\Video;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository {

    public function getPromotedVideos() {
        return $this->createQueryBuilder("v")
                        ->where("v.isFront = true")
                        ->where("v.isMain = false")
                        ->getQuery()
                        ->execute();
    }

    public function getMainVideos() {
        return $this->createQueryBuilder("v")
                        ->where("v.isFront = true")
                        ->where("v.isMain = true")
                        ->getQuery()
                        ->execute();
    }

    public function getVideos(Category $category = null) {
        $query = $this->createQueryBuilder("v");
        if ($category)
        {
            $query->where("v.category = :category");
            $query->setParameters(array(
                "category" => $category
            ));
        }
        return $query->getQuery()->execute();
    }

    public function getAllVideos() {
        return $this->createQueryBuilder("v")
                        ->innerJoin("v.category", "c")
                        ->getQuery()
                        ->execute();
    }

}
